module.exports = {
    INITIAL:"INITIAL",
    SELL_REPAY: "SELL_REPAY",
    SELL_SHORT: "SELL_SHORT",
    BUY_REPAY: "BUY_REPAY",
    BUY_LONG: "BUY_LONG",
    BUY_CLOSED: "BUY_CLOSED",
    SELL_CLOSED: "SELL_CLOSED",
    WAIT_FOR_LONG: "WAIT_FOR_LONG",
    WAIT_FOR_SHORT: "WAIT_FOR_SHORT",
}